from .user import User
from .rol import Rol
from .user_rol import UserRol
from .administrative_type import AdministrativeType
from .administrative import Administrative
from .professor_type import ProfessorType
from .professor import Porfesor
from .student import Student
from .user_academic_council import UserAcademicCouncil
from .user_research_group import UserResearchGroup