version: '3.9'

services:
    postgres-db-auth:
        build:
            context: ../config_db
            dockerfile: Dockerfile
        volumes:
            - ../db/postgres:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - auth-network

    backend-auth:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8003:8010"
        env_file:
            - ../.env
        networks:
            - auth-network
        depends_on:
            - postgres-db-auth
        restart: on-failure

networks:
    auth-network:
        driver: bridge

