version: '3.9'

services:
    postgres-db-auth:
        build:
            context: ../config_db
            dockerfile: Dockerfile
        volumes:
            - ../db/postgres:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - auth-network

    mongo-db-auth:
        container_name: 'mongo'
        image: mongo:4.4
        restart: always
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        networks:
            - auth-network
        volumes:
            - ../db/mongo-data:/data/db

    backend-auth:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8003:8010"
            - "10001:10001"
        env_file:
            - ../.env
        networks:
            - auth-network
        depends_on:
            - postgres-db-auth
            - mongo-db-auth
        restart: on-failure
    

networks:
    auth-network:
        driver: bridge

